version: '3.4'
services:
  mariadb:
    image: ragedunicorn/mariadb:1.0.4-stable
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - com.ragedunicorn.mariadb.root_password
      - com.ragedunicorn.mariadb.app_user
      - com.ragedunicorn.mariadb.app_user_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.mariadb.environment: "prod"
      com.ragedunicorn.mariadb.description: "MariaDB"
volumes:
  mariadb_data: {}
secrets:
  com.ragedunicorn.mariadb.root_password:
    external: true
  com.ragedunicorn.mariadb.app_user:
    external: true
  com.ragedunicorn.mariadb.app_user_password:
    external: true
